apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lebondeveloppeur/backend-s8-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: MONGO_USER
              valueFrom: { secretKeyRef: { name: mongo-secret, key: MONGO_APP_USER } }
            - name: MONGO_PASSWORD
              valueFrom: { secretKeyRef: { name: mongo-secret, key: MONGO_APP_PASSWORD } }
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongo.myapp.svc.cluster.local:27017/mydb?authSource=mydb&retryWrites=true&w=majority"
          # readinessProbe:
          #   httpGet: { path: /health/ready, port: 8080 }
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet: { path: /health/live, port: 8080 }
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
