name: Build, Push, and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# permissions:
#   contents: read

# env:
#   REPO: mern-ecommerce-store
#   TAG: latest

jobs:
  # build-and-push:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     # Backend image
  #     - name: Build & Push backend
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: ./backend
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}-backend:${{ env.TAG }}
  #         cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}-backend:buildcache
  #         cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}-backend:buildcache,mode=max

  #     # Frontend image
  #     - name: Build & Push frontend
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: ./frontend
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}-frontend:${{ env.TAG }}
  #         cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}-frontend:buildcache
  #         cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}-frontend:buildcache,mode=max

  deploy:
    # needs: build-and-push
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout (for k8s manifests)
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Write kubeconfig from secret
        run: |
               mkdir -p "$HOME/.kube"
               cat > "$HOME/.kube/config" <<'EOF'
                ${{ secrets.KUBE_CONFIG }}
                EOF
                sed -i 's/\r$//' "$HOME/.kube/config"
                chmod 600 "$HOME/.kube/config"
                head -n 5 "$HOME/.kube/config"
                kubectl get all -A

      # - name: Set image tags in manifests (optional)
      #   run: |
      #     # Update images to the freshly pushed tags if needed
      #     # Example with yq or sed; comment out if your k8s yaml already references :latest
      #     # sed -i "s|image: .*/${{ env.REPO }}-backend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}-backend:${{ env.TAG }}|g" k8s/*.yaml
      #     # sed -i "s|image: .*/${{ env.REPO }}-frontend:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO }}-frontend:${{ env.TAG }}|g" k8s/*.yaml
      #     true

      - name: Deploy to Kubernetes
        run: |
           cat $HOME/.kube/config
           kubectl get all -A
      #     kubectl rollout status deploy/backend --timeout=120s || true
      #     kubectl rollout status deploy/frontend --timeout=120s || true

